vmware-tanzu/asset-relocation-tool-for-kubernetes

- .github/workflows/golangci-lint.yml
- .golangci.yml
- Makefile
- code-header-template.txt
- internal/image.go
- internal/image_change.go
- internal/image_template.go
- internal/image_template_test.go
- internal/rewrite_action.go
- internal/rewrite_action_test.go
- internal/yamlops/helpers_test.go
- internal/yamlops/nodesearch.go
- internal/yamlops/nodesearch_test.go
- internal/yamlops/scanner.go
- internal/yamlops/scanner_test.go
- internal/yamlops/yamlops.go
- internal/yamlops/yamlops_test.go
- main.go
- pkg/mover/chart.go
- test/chart_move_feature_test.go
- test/common_steps.go
- test/features_suite_test.go
- test/test_helpers.go
- test/version_test.go
Closes https://github.com/vmware-tanzu/asset-relocation-tool-for-kubernetes/issues/45
* Adds golangcli-lint configuration. The configuration is based in the one in a couple of projects, Helm, carvels/kapp-controller 
* Updates the `lint` makefile target
* Updates code to meet the linter standards, i.e updates the headers
* Adds a golang-ci Github action that runs on PR and merges in `main`. Enabled in this PR already (see checks)
Linters enabled with that configuration
```bash
$ golangci-lint linters                                           
Enabled by your configuration linters:                                         
deadcode: Finds unused code [fast: false, auto-fix: false]
dupl: Tool for code clone detection [fast: true, auto-fix: false]
gofmt: Gofmt checks whether code was …
```
> feat(ci): Add golang-ci configuration and CI action

- .golangci.yml
- cmd/chart.go
- internal/image_template.go
- pkg/mover/chart.go
- pkg/mover/chart_test.go
- pkg/mover/doc_test.go
- test/chart_move_feature_test.go
Split from https://github.com/vmware-tanzu/asset-relocation-tool-for-kubernetes/pull/37
Changes the mover constructor signature to not to require the caller to import and load neither the Helm Chart nor the imagehints file. A path to those will suffice now. 
> feat: Simplify Mover interface

- cmd/chart.go
- pkg/mover/chart.go
- pkg/mover/chart_test.go
- test/external_test.go
- test/fixtures/testchart.images.yaml
- test/fixtures/testchart/charts/subchart/.helmignore
- test/fixtures/testchart/charts/subchart/Chart.yaml
- test/fixtures/testchart/charts/subchart/values.yaml
Some minor tweaks in the output based on my experience using the tool. 
They could be summarized as
* Standardize on future tense. Fixes https://github.com/vmware-tanzu/asset-relocation-tool-for-kubernetes/issues/34
* Removes chart path from the rewrite `path` shown to the user. Fixes https://github.com/vmware-tanzu/asset-relocation-tool-for-kubernetes/issues/38
* Show location of the final file
* Indicate explicitly if an image exists
* Move some of the logging capabilities inside the library so other consumers can also get debugging information
* Remove some redundant information
Example output
```
go run main.go chart move --image-patterns examples/chart-with-subcharts/image-hints.yaml --registry projects.registry.vmware.com --repo-prefix relocated/example2 …
```
> fix(ux): Tweak relocation output

- Makefile
- README.md
- cmd/chart.go
- go.mod
- internal/image_template_test.go
- internal/internalfakes/fake_image_interface.go
- internal/rewrite_action.go
- internal/rewrite_action_test.go
- internal/yamlops/nodesearch_test.go
- internal/yamlops/scanner_test.go
- internal/yamlops/yamlops_test.go
- main.go
- pkg/mover/chart.go
- pkg/mover/chart_test.go
- test/chart_move_feature_test.go
- test/common_steps.go
Refs https://github.com/vmware-tanzu/asset-relocation-tool-for-kubernetes/issues/54
Removed the major version namespace in the module name. We have never had a v1 so a v2 from the get go does not make much sense.
> chore: remove /v2 from module path

- internal/image_template_test.go
- internal/internal_suite_test.go
- internal/rewrite_action.go
- pkg/mover/chart.go
Supersedes https://github.com/vmware-tanzu/asset-relocation-tool-for-kubernetes/pull/63
This patch does the following
- Fixes
- Adds a test-suite file to make sure that those unit tests are run, thanks @petewall for the catch
- Fixes a regression in which we were adding rewrite rules even if it's value was the same and in practice meant a no-op
- Fixes a regression in where if only the registry rule was passed and the template was registry+path, the rewrite was not working as expected. 
- Cleanup
- It removes the `Digest` property from the Apply Rewrite rules inputs since we do not allow rewriting it at this point and it was confusing. Currently the only rewrite sources are the repoPrefix and the registry
- Feature 
- By default we try to add the content digest to the image path unless …
> Fix apply method and apply default hash

- .golangci.yml
- code-header-template.txt
- pkg/mover/doc_test.go
* Re-enabled default linters
* Alphabatized enabled linter list
* Removed custom year argument in favor of one that is pre-provided by goheader
* Fixed a singular issue from the new linter rules
Signed-off-by: Pete Wall <pwall@vmware.com>
> Lint improvements

- cmd/chart.go
- pkg/mover/chart.go
- pkg/mover/rewrite_rules.go
- pkg/mover/rewrite_rules_test.go
- test/features/chart_move_feature_test.go
- test/features/chart_move_input_validation_feature_test.go
This adds validation to the `--registry` and `--repo-prefix` parameters.
It splits the existing feature test into an input validation feature test and a chart move feature test (which is still disabled until I figure out a way to make a fake image registry to talk to).
Signed-off-by: Pete Wall <pwall@vmware.com>
> Validate registry and repository prefix user inputs

- pkg/mover/tar.go
Seems that even docker save does not set any user or group info per file to be set in the tar. When extracting they will be populated as per ownership of the running process, which is fine.
See context here:
https://github.com/vmware-tanzu/asset-relocation-tool-for-kubernetes/pull/82#discussion_r756467402
and here:
https://gist.github.com/migmartri/06fcb75e4f9d88e1e310472ca5d672d2
Signed-off-by: Jose Luis Vazquez Gonzalez <josvaz@vmware.com>
> Do not set user/group per file when tarring

- README.md
Updated the main documentation to include
* Renames from pattern file to hints file
* Indicate that an embedded file is also supported
* Link to the subcharts example
> fix(documentation): update readme with information about the hints file

- internal/image_change.go
- pkg/mover/chart.go
- pkg/mover/chart_test.go
- test/external/external_test.go
If the original image is tagged, use that tag when pushing the resulting image, but still prefer to write the digest version to the Helm chart.
Closes #16
> Always push the tagged version, but write the digest version

- go.mod
- go.sum
- vendor/github.com/opencontainers/runc/libcontainer/user/user.go
- vendor/modules.txt
Signed-off-by: Jose Luis Vazquez Gonzalez <josvaz@vmware.com>
To try to avoid this reported vulnerability:
https://github.com/vmware-tanzu/asset-relocation-tool-for-kubernetes/security/dependabot/go.mod/github.com%2Fopencontainers%2Frunc/open
> Upgrade runc due to sec vulnerability

- Makefile
- pkg/mover/registry_test.go
- test/registry/Dockerfile
This PR changes to a lighter chart to be tested in the local-registry testing.
It also adds some optional or manually triggered tests to check what happens when the target registry is fresh, empty and how that affects to move vs save/load performance.
We might not want to merge this second part, but I think it is interesting to check as part of #104 discussions
> Lighter registry test

- pkg/mover/rewrite_rules.go
- pkg/mover/rewrite_rules_test.go
- test/external/external_test.go
- test/features/chart_move_input_validation_feature_test.go
- test/fixtures/complex-chart/.relok8s-images.yaml
- test/fixtures/complex-chart/Chart.yaml
- test/fixtures/complex-chart/charts/subchart-1/Chart.yaml
- test/fixtures/complex-chart/charts/subchart-1/values.yaml
- test/fixtures/complex-chart/charts/subchart-10/Chart.yaml
- test/fixtures/complex-chart/charts/subchart-10/values.yaml
- test/fixtures/complex-chart/charts/subchart-2/Chart.yaml
- test/fixtures/complex-chart/charts/subchart-2/values.yaml
- test/fixtures/complex-chart/charts/subchart-3/Chart.yaml
- test/fixtures/complex-chart/charts/subchart-3/values.yaml
- test/fixtures/complex-chart/charts/subchart-4/Chart.yaml
- test/fixtures/complex-chart/charts/subchart-4/values.yaml
- test/fixtures/complex-chart/charts/subchart-5/Chart.yaml
- test/fixtures/complex-chart/charts/subchart-5/values.yaml
- test/fixtures/complex-chart/charts/subchart-6/Chart.yaml
- test/fixtures/complex-chart/charts/subchart-6/values.yaml
- test/fixtures/complex-chart/charts/subchart-7/Chart.yaml
- test/fixtures/complex-chart/charts/subchart-7/values.yaml
- test/fixtures/complex-chart/charts/subchart-8/Chart.yaml
- test/fixtures/complex-chart/charts/subchart-8/values.yaml
- test/fixtures/complex-chart/charts/subchart-9/Chart.yaml
- test/fixtures/complex-chart/charts/subchart-9/values.yaml
- test/fixtures/complex-chart/values.yaml
Adds a chart that uses global compound registry and repository and subcharts with image names.
Adjusts the registry rule validation to validate the full path if the registry rule was provided.
Signed-off-by: Pete Wall <pwall@vmware.com>
> Add test to protect a certain partner/customer use-case

- .github/workflows/golangci-lint.yml
- internal/canonical_docker_image.go
- pkg/mover/intermediate.go
Based on the experience an implementation hints showed here https://github.com/vmware-tanzu/asset-relocation-tool-for-kubernetes/pull/121, thanks @josvazg 
As you can see in [this example code](https://gist.github.com/migmartri/0eb70f4e12c8782a526f52413c5266cf) the issue appears in the use-case where an image is dumped into a tarball first and then extracted+pushed. This is because the image manifest does not get stored in the tarball and gocontainerregistry crafts [[1]](https://github.com/google/go-containerregistry/blob/main/pkg/v1/tarball/image.go#L319) and marshalls [[2]](https://github.com/google/go-containerregistry/blob/7adcadef6bc8adf07cc587a5a5a443afe7603d54/pkg/v1/partial/with.go#L164) a new one before pushing it to the destination registry. 
This should be ok except that …
> fix(intermediate): Stable content digest from intermediate bundle

- .golangci.yml
- code-header-template.txt
Updates our linter configuration to accept copyright headers that span from 2021 to 2022. This will allow us to preserve the existing headers while allowing us to add up to date ones for new files.
I've read in [multiple](https://stackoverflow.com/a/2391555) [places](https://opensource.google/docs/copyright/#the-year) that ideally the original date should be retained, 
> fix(linter): Allow multiple copyright years

- .github/workflows/goreleaser.yml
It seems that our new release action does not work, it's like github is stuck with a previous version of another workflow called `release` that was added some time ago as POC in a branch.
In order to unlock this I've performed two changes, to change the name of the workflow file and it's actual identifier.
> fix: rename goreleaser action

- .github/workflows/goreleaser.yml
- .goreleaser.yml
- Dockerfile
Update goreleaser to also build container images with latest versions of the binary inside pushed to Github packages repository `ghcr.io/vmware-tanzu/asset-relocation-tool-for-kubernetes`
The Dockerfile has also been updated to leverage the binary created by goreleaser itself
Tested it and an image was built and pushed as expected https://github.com/vmware-tanzu/asset-relocation-tool-for-kubernetes/pkgs/container/asset-relocation-tool-for-kubernetes/13030106?tag=v0.3.61-pre https://github.com/vmware-tanzu/asset-relocation-tool-for-kubernetes/actions/runs/1683473654
Refs https://github.com/vmware-tanzu/asset-relocation-tool-for-kubernetes/issues/127
> feat: Release container images into Github Packages repository

- Dockerfile
During the implementation of https://github.com/vmware-tanzu/asset-relocation-tool-for-kubernetes/pull/128 a regression was added which dropped some required deps.
This patch puts them back.
> fix: add missing deps in upstream Dockerfile

- ci/Dockerfile
- ci/pipeline.yaml
We are currently running the golangci-lint twice, once in the github action and also in the concourse pipeline. 
In my opinion the execution in the internal pipeline should be remove because of
- We are moving away from the use of a monolithic internal pipeline step in favor of public facing single purpose Github actions
- By running it in two places, by two different systems we can run into inconsistencies, for example, the golangci github action is configured in a specific way that concourse doesn't know about.   
> chore: remove linter from concourse

- pkg/mover/chart_test.go
Fix a brittle test in where the issue was that the .Dependencies() method returns a slide of *Chart in arbitrary order. This means that in the case in where the order was inverted, the second level dep array access was accessing to a nil subchart.
By sorting the array of dependencies, the test become deterministic. 
> fix: update brittle test case

- cmd/chart.go
- pkg/mover/auth.go
- pkg/mover/chart.go
- pkg/mover/registry_test.go
This patch changes the current containers authentication mechanism so instead of falling back to the default keychain, its use must be explicitly set.
The reason for this change is because while using relok8s as a library from charts-syncer I noticed that the fallback didn't make sense in that tool and there was not an easy way to disable it without providing bogus credentials, which also broke anonymous access to public registries.
From the POV of relok8s, nothing has changed, the CLI itself indicates that it wants to use the local keychain
> feat: container keychains exclusion

- cmd/chart.go
- pkg/mover/auth.go
- pkg/mover/auth_test.go
- pkg/mover/chart.go
- pkg/mover/registry_test.go
Validates the correctness of the provided OCI credentials. Additionally it updates the embed structs to be pointer to struts for consistency and simplification on the side of the caller (the caller does not always need to provide an empty struct)
FIxes https://github.com/vmware-tanzu/asset-relocation-tool-for-kubernetes/issues/143
> feat: validate credentials

- go.mod
- go.sum
- vendor/github.com/docker/distribution/registry/client/auth/challenge/authchallenge.go
- vendor/modules.txt
Refs https://github.com/advisories/GHSA-qq97-vm5h-rrhg
Note: Github's dependabot integration does not work.
> chore(security): Fix OCI Manifest Type Confusion vulnerability 

- .github/workflows/golangci-lint.yml
- pkg/mover/chart.go
- pkg/mover/chart_test.go
`groupChangesByChart` was returning a map but we expected the result sto be ordered, in particular hierarchical ordered preferably.
This change turns `groupChangesByChart` into `orderedChangesByChart` by taking the mp generated before and passing it to `orderByChartHierarchy` which builds an array of `ChartChanges` and enforces the expected hierarchical order leveraging the chart full path: least deep paths go first, at the same depth level order alphabetically.
Signed-off-by: Jose Luis Vazquez Gonzalez <josvaz@vmware.com>
> Enforce hierarchical chart changes ordering

- examples/concourse-pipeline/image-hints.yaml
- examples/concourse-pipeline/pipeline.yaml
The concourse example pipeline failed because nginx went to version 10.x and the image hints file failed.
I took this opportunity to extract it into its own file.
> Update concourse example

- ci/Dockerfile
Signed-off-by: Pete Wall <pwall@vmware.com>
This fixes a strange apt issue seen only in CI when using the non-pinned version.
> Pin test-image to 20.04

- .github/workflows/golangci-lint.yml
- go.mod
- go.sum
- vendor/modules.txt
Manual attempt to bump version after dependabot issue.
**Also bump Go to 1.20** as Go 1.18 is now out of maintenance.
> Bump docker from 23.0.1+incompatible to 23.0.3+incompatible

- cmd/chart.go
- pkg/mover/chart.go
- pkg/mover/intermediate.go
- pkg/mover/tar.go
At https://github.com/vmware-tanzu/asset-relocation-tool-for-kubernetes/pull/210 I fixed some errors returning by the linter action in the main branch. However, it seems for that action to pass, we should also fix the warnings.
```
Warning: unused-parameter: parameter 'cmd' seems to be unused, consider removing or renaming it as _ (revive)
Warning: redefines-builtin-id: redefinition of the built-in function close (revive)
Warning: redefines-builtin-id: redefinition of the built-in function close (revive)
Warning: unused-parameter: parameter 'format' seems to be unused, consider removing or renaming it as _ (revive)
Warning: unused-parameter: parameter 'i' seems to be unused, consider removing or renaming it as _ (revive)
Warning: unused-parameter: parameter 'log' seems to be unused, …
```
> chore: fix also the linter warnings

- .github/workflows/goreleaser.yml
- .goreleaser.yml
Updates .goreleaser file format to work with the latest version:
* [The replacement section has been deprecated](https://goreleaser.com/deprecations/?h=replacements#archivesreplacements)
* The `--rm-dist` flag has been renamed to `--clean`
> chore: update goreleaser.yml so it is compartible with latest version
